### ISSUE TITLE
Apollo grid scroll

### ISSUE THREAD

**Issue by VeraRibeiro** [underfisk/apollo-spreadsheet#18]
Copy of Issue #1276, creating in Apollo 

**Is your feature request related to a problem? Please describe.**
When scrolling on apollo grid on a mac, the scroll will appear on top of the checkboxes
This only happens in mac on scroll with dynamic auto-hide, not with scroll always visible

![Screenshot 2020-11-25 at 20 08 17](https://user-images.githubusercontent.com/47228478/100276849-17ee7e00-2f5a-11eb-8bc7-a0097acdd415.png)

**Describe the solution you'd like**
Scroll should appear on the right side of the checkbox column
We should give a small margin where the scroll would fit

**Comment by underfisk** [comment]
This must replace our current scroll width library that calculated the width of the scrollbar to be removed from the container width, i'll look forward

**Comment by underfisk** [comment]
Issue has been fixed by replacing our scroll calculation library
