### ISSUE TITLE
Apollo grid indentation highlight

### ISSUE THREAD

**Issue by VeraRibeiro** [underfisk/apollo-spreadsheet#23]
**Is your feature request related to a problem? Please describe.**
Indentation highlight is lost on merge cells. Apollo doesn't recognise the parent, resulting in only the current cell to be highlighted

**Describe the solution you'd like**
Highlight needs to be kept in the whole row, and follow the indentation

![Screenshot 2021-01-28 at 15 20 46](https://user-images.githubusercontent.com/47228478/106159277-862f0700-617c-11eb-9cad-11228fa5aeab.png)

![Screenshot 2021-01-28 at 15 21 34](https://user-images.githubusercontent.com/47228478/106159294-8929f780-617c-11eb-89d3-1ddd0821f4cb.png)

I opened this issue in Apollo, but the milestone is for  TOP5.03

**Comment by underfisk** [comment]
@VeraRibeiro This issue is related when merged cells are bigger than the current viewport/screen size?

**Comment by VeraRibeiro** [comment]
I don't think so, in that example that I placed all the cells fit on the viewport

**Comment by underfisk** [comment]
@VeraRibeiro Is there any way I can replicate the issue? In those screenshots I have no idea of your current viewport, can you create a screenshot of the whole viewport of the table?

**Comment by VeraRibeiro** [comment]
Yes exactly, the first child on the row keeps the highlight, but on the 2nd, etc it disappears

**Comment by underfisk** [comment]
@VeraRibeiro Did it start happening in every project or only in some specifics or some specific conditions? That would be good to know in order to know which project I can copy to replicate the issue

**Comment by VeraRibeiro** [comment]
@underfisk in every project. I usually test in the TOP V 5.02 “Apollo” since it's the largest project, but it's happening everywhere (both stage and localhost, new or ongoing projects)

**Comment by underfisk** [comment]
@VeraRibeiro Okay thanks
